server {
    listen 80;
    server_name rootssh.me www.rootssh.me;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name rootssh.me www.rootssh.me;

    ssl_certificate /etc/letsencrypt/live/rootssh.me/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/rootssh.me/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /api/ {
        proxy_pass http://node-app:3000/;
    }
}
